import Vue from 'vue'
import { Button, Container, Header, Aside, Main, Menu, Submenu, MenuItemGroup, MenuItem, Table, TableColumn, Pagination, Popover, Tag, Steps, Step, Tooltip, Timeline, TimelineItem, Calendar, Tabs, TabPane, Form, FormItem, Input, Select, Option,  Col, DatePicker, TimePicker, Switch, CheckboxGroup, Checkbox,  RadioGroup, Radio,Upload, Rate, Image, InfiniteScroll, Breadcrumb, BreadcrumbItem, Collapse, CollapseItem, Message, MessageBox, Dialog, Drawer} from 'element-ui'

Vue.use(Button)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Popover)
Vue.use(Tag)
Vue.use(Steps)
Vue.use(Step)
Vue.use(Tooltip)
Vue.use(TimelineItem)
Vue.use(Timeline)
Vue.use(Calendar)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Select)
Vue.use(Option)
Vue.use(Col)
Vue.use(DatePicker)
Vue.use(TimePicker)
Vue.use(Switch)
Vue.use(CheckboxGroup)
Vue.use(Checkbox)
Vue.use(RadioGroup)
Vue.use(Radio)
Vue.use(Upload)
Vue.use(Rate)
Vue.use(Image)
Vue.use(InfiniteScroll)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Dialog)
Vue.use(Drawer)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
